import './globals.scss';
import '@/node_modules/react-modal-video/scss/modal-video.scss';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/index';
import AppProviderContainer from './providers/AppProviderContainer';
// import '../public/assets/css/main.css'

export const metadata = {
  title: 'CrCrypto',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.svg',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppProviderContainer>
          {/* <Navbar /> */}
          {children}
          {/* <Footer /> */}
        </AppProviderContainer>
      </body>
    </html>
  )
}
